In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\sivau\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
data=pd.read_csv("Salary_Data.csv")

In [3]:
# from pandas_profiling import ProfileReport
# profile=ProfileReport(data)
# profile.to_file(output_file="output.html")

In [4]:
# pip install --upgrade pandas


# Feature Engineering

In [5]:
data.shape


(30, 2)

# Feature Scaling

#  StandarScaler

In [6]:
data.sample(5)

YearsExperience   Salary
7               3.2  54445.0
0               1.1  39343.0
12              4.0  56957.0
3               2.0  43525.0
19              6.0  93940.0

In [7]:
x=data

In [8]:
x.sample(3)

YearsExperience    Salary
19              6.0   93940.0
29             10.5  121872.0
28             10.3  122391.0

In [9]:
y=data.iloc[:,1:]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test=train_test_split(x,test_size=0.3,random_state=10)

In [12]:
x_train.shape,x_test.shape#y_train.shape,y_test.shape

((21, 2), (9, 2))

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler=StandardScaler() #(x-mean of  x) / Standard Deviation

In [15]:
scaler.fit(x_train)

StandardScaler()

In [16]:
x_train_scaler=scaler.transform(x_train)
x_test_scaler=scaler.transform(x_test)

In [17]:
x_train_scaler

array([[-1.52728034, -1.23378219],
       [ 0.13105376,  0.53114443],
       [-0.39820181, -0.68265626],
       [ 0.09577005,  0.06612962],
       [-0.92745737, -0.71818773],
       [-0.57462033, -0.87924398],
       [ 0.90729525,  1.26588041],
       [ 1.08371377,  1.10389982],
       [ 1.64825304,  1.58307546],
       [ 0.80144414,  0.80334282],
       [-0.60990403, -0.60475325],
       [ 1.36598341,  1.38260552],
       [ 1.71882045,  1.56388625],
       [-0.85688996, -0.55938685],
       [ 1.18956489,  0.96158909],
       [-0.18649958, -0.50082094],
       [-0.11593217,  0.12990878],
       [-1.59784775, -1.48749386],
       [-0.25706699, -0.43023866],
       [-1.209727  , -1.46723242],
       [-0.68047144, -0.82766605]])

In [18]:
# x_train_scaler,x_test_scaler

# Normalization Techniques

#  MinMaxScaler

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
Minmax=MinMaxScaler() # x - x(min) / x(max) - x(min)

In [21]:
Minmax.fit(x_train)

MinMaxScaler()

In [22]:
x_train_Minmax=Minmax.transform(x_train)
x_test_Minmax=Minmax.transform(x_test)

In [23]:
x_train_Minmax,x_test_Minmax

(array([[0.0212766 , 0.08262691],
        [0.5212766 , 0.65741499],
        [0.36170213, 0.26211348],
        [0.5106383 , 0.50597245],
        [0.20212766, 0.25054186],
        [0.30851064, 0.19809026],
        [0.75531915, 0.89669829],
        [0.80851064, 0.84394567],
        [0.9787234 , 1.        ],
        [0.72340426, 0.74606252],
        [0.29787234, 0.28748435],
        [0.89361702, 0.93471246],
        [1.        , 0.9937506 ],
        [0.22340426, 0.30225893],
        [0.84042553, 0.79759898],
        [0.42553191, 0.32133224],
        [0.44680851, 0.52674357],
        [0.        , 0.        ],
        [0.40425532, 0.34431895],
        [0.11702128, 0.00659859],
        [0.27659574, 0.21488778]]),
 array([[ 0.60638298,  0.6309002 ],
        [ 0.22340426,  0.18184664],
        [ 0.19148936,  0.20830122],
        [ 0.04255319, -0.01941046],
        [ 0.09574468,  0.05035642],
        [ 0.63829787,  0.70958963],
        [ 0.31914894,  0.21358732],
        [ 0.90425532,  0.8825257

# Robust Scaler

In [24]:
from sklearn.preprocessing import RobustScaler

In [25]:
Rscaler = RobustScaler() #x - x(median) / 75% val - 25% val

In [26]:
Rscaler.fit(x_train)

RobustScaler()

In [27]:
x_train_Rscaler=Rscaler.transform(x_train)
x_test_Rscaler = Rscaler.transform(x_test)

In [28]:
x_train_Rscaler,x_test_Rscaler

(array([[-0.84444444, -0.47836327],
        [ 0.2       ,  0.57232787],
        [-0.13333333, -0.15026853],
        [ 0.17777778,  0.29549657],
        [-0.46666667, -0.17142102],
        [-0.24444444, -0.26730058],
        [ 0.68888889,  1.00972883],
        [ 0.8       ,  0.913299  ],
        [ 1.15555556,  1.19856049],
        [ 0.62222222,  0.73437225],
        [-0.26666667, -0.10389153],
        [ 0.97777778,  1.07921729],
        [ 1.2       ,  1.18713682],
        [-0.42222222, -0.07688413],
        [ 0.86666667,  0.82857898],
        [ 0.        , -0.04201884],
        [ 0.04444444,  0.3334654 ],
        [-0.88888889, -0.62940218],
        [-0.04444444,  0.        ],
        [-0.64444444, -0.6173402 ],
        [-0.31111111, -0.23659535]]),
 array([[ 0.37777778,  0.52385983],
        [-0.42222222, -0.29699331],
        [-0.48888889, -0.24863532],
        [-0.8       , -0.66488378],
        [-0.68888889, -0.53735253],
        [ 0.44444444,  0.66770118],
        [-0.22222222, -0.2

# Encoding Technique

In [29]:
df1=pd.read_csv("Fish.csv")

In [30]:
df1["Species"].value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [31]:
df1.sample(2)

Species  Weight  Length1  Length2  Length3   Height   Width
33   Bream   975.0     37.4     41.0     45.9  18.6354  6.7473
83   Perch   115.0     19.0     21.0     22.5   5.9175  3.3075

In [32]:
from sklearn.preprocessing import OrdinalEncoder

In [33]:
df2=pd.read_csv("insurance.csv")

In [34]:
df2.sample(2)

age   sex     bmi  children smoker     region      charges
964   52  male  36.765         2     no  northwest  26467.09737
512   51  male  22.420         0     no  northeast   9361.32680

In [35]:
df3=df2[["sex","region","children"]]

In [36]:
df3["region"].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

# Ordinal Encoder 

In [37]:
x=df3

In [38]:
y=df3.iloc[:,2:]

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [42]:
oe=OrdinalEncoder()

In [43]:
oe.fit(x_train)

OrdinalEncoder()

In [44]:
 oe.transform(x_train)

array([[0., 0., 1.],
       [1., 2., 0.],
       [1., 3., 1.],
       ...,
       [0., 3., 1.],
       [1., 3., 0.],
       [1., 2., 1.]])

In [45]:
x_train

sex     region  children
428   female  northeast         1
226     male  southeast         0
867     male  southwest         1
397     male  southeast         0
300     male  northeast         3
...      ...        ...       ...
1180  female  northeast         1
1147  female  northwest         0
527   female  southwest         1
1149    male  southwest         0
1289    male  southeast         1

[936 rows x 3 columns]

In [46]:
oe.transform(x_test)

array([[0., 1., 3.],
       [0., 1., 0.],
       [1., 3., 1.],
       ...,
       [1., 0., 1.],
       [1., 2., 0.],
       [0., 2., 1.]])

# Label Encoder

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [48]:
y_train,y_test=train_test_split(df1.iloc[:,0],random_state=10,test_size=0.2)

In [49]:
# df1.iloc[:,0]

In [50]:
le=LabelEncoder()

In [51]:
le.fit(y_train)

LabelEncoder()

In [52]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [53]:
y_train

array([2, 4, 1, 0, 6, 3, 6, 5, 2, 2, 2, 6, 2, 4, 3, 2, 0, 2, 1, 4, 2, 0,
       1, 2, 4, 2, 0, 4, 2, 2, 5, 3, 4, 0, 5, 0, 0, 2, 2, 5, 4, 5, 5, 4,
       2, 2, 4, 2, 3, 3, 0, 3, 2, 0, 3, 2, 2, 0, 3, 4, 3, 2, 2, 0, 0, 4,
       2, 2, 2, 3, 2, 2, 0, 4, 0, 2, 2, 1, 2, 5, 5, 5, 3, 2, 0, 0, 2, 0,
       0, 3, 2, 0, 0, 4, 6, 0, 1, 2, 0, 2, 2, 2, 0, 2, 3, 5, 0, 1, 2, 2,
       2, 4, 3, 2, 0, 2, 4, 0, 2, 0, 5, 2, 2, 1, 0, 2, 0])

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
ohe=OneHotEncoder()

In [56]:
ohe.fit(x_train)

OneHotEncoder()

In [57]:
x_train=ohe.transform(x_train)

In [58]:
x_test=ohe.transform(x_test)

In [59]:
x_train.toarray()

array([[1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [60]:
x_train.shape

(936, 12)

# Column Transformer (Simple Imputer)

In [61]:
from sklearn.impute import SimpleImputer

In [62]:
data=pd.read_csv("insurance.csv")
print(data)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [63]:
x=data.iloc[:,:6]

In [85]:
y=data["region"]

In [86]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [87]:
oe=OneHotEncoder()

In [88]:
oe.fit(x_train)

OneHotEncoder()

In [89]:
x_train_oe=oe.transform(x_train)
x_test_oe=oe.transform(x_test)

ValueError: Found unknown categories [15.96, 17.67, 18.3, 18.5, 18.6, 19.0, 19.19, 20.045, 20.425, 20.79, 21.01, 21.09, 21.5, 22.04, 23.0, 23.1, 23.8, 23.9, 24.53, 25.08, 25.52, 25.65, 26.07, 26.2, 26.29, 26.84, 27.28, 27.3, 28.3, 28.8, 29.165, 29.2, 29.4, 29.45, 29.5, 29.545, 30.0, 30.36, 30.97, 31.0, 31.24, 31.445, 31.635, 32.1, 32.12, 32.34, 32.78, 33.55, 33.88, 35.09, 35.1, 35.15, 35.5, 35.6, 36.005, 36.195, 36.2, 36.4, 36.7, 37.145, 37.9, 39.27, 39.4, 39.8, 39.9, 40.945, 42.75, 42.94, 43.01, 43.34, 44.7, 46.09, 46.53, 47.6] in column 2 during transform

In [90]:

from sklearn.compose import ColumnTransformer

In [98]:
transformer=ColumnTransformer(transformers=[
    ("tnf1",OrdinalEncoder(categories=[["female","male"]]),["sex"]),
    ("tnf3",OrdinalEncoder(categories=[["yes","no"]]),["smoker"]),
    ("tnf2",OneHotEncoder(),["region","children"])
],remainder="passthrough")

In [99]:
transformer.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1',
                                 OrdinalEncoder(categories=[['female',
                                                             'male']]),
                                 ['sex']),
                                ('tnf3',
                                 OrdinalEncoder(categories=[['yes', 'no']]),
                                 ['smoker']),
                                ('tnf2', OneHotEncoder(),
                                 ['region', 'children'])])

In [102]:
x_train_trans=transformer.transform(x_train)

In [109]:
x_train_trans.shape

(936, 14)